### ISSUE TITLE
아이템 10. equals는 일반 규약을 지켜 재정의하라

### ISSUE THREAD

**Issue by ZhenxiKim** [WanOnPreStudy/EffectiveJavaStudy#15]

**Comment by jueun275** [comment]
65p 에 
Object  외의 타입을 매개변수로 받는 equals 메서드는 선언하지 말자

```java
public boolean equals(MyClass o) {
    . . .
}
```

> 기본 equals를 그대로 둔 채로 추가한 것일지라도, 이처럼  '타입을 구체적으로 명시한' equals는 오히려 해가 된다. 
이 메서드는 하위 클래스에서의 `@Override` 애너테이션이 긍정 오류를 내게 하고 보안 측면에서도 잘못된 정보를 준다.

라고만 나와있어서 이해가 잘 안되는데 

'타입을 구체적으로 명시한' equals의 문제점을 좀 더 자세히 설명해 주실 수 있나요? ㅠ
