### ISSUE TITLE
아이템 15. 클래스와 멤버의 접근 권한을 최소화하라

### ISSUE THREAD

**Issue by ZhenxiKim** [WanOnPreStudy/EffectiveJavaStudy#24]
이해되지 않거나 같이 토의하고싶은 부분 comment로 올려주세요

**Comment by inhwanK** [comment]
97쪽 4번째 문단을 보면
<pre>
한 클래스에서만 사용하는 package-private 톱레벨 클래스나 인터페이스는 
이를 사용하는 클래스 안에 private static으로 중첩시켜보자
</pre>

라고 나와있는데 private static으로 중첩시킨다는게 어떤 의미인지 모르겠네용

**Comment by gutenLEE** [comment]
다른 블로그 글도 참고해보니 클래스 단위 접근제한을 무조건 package-private 으로 제한하는게 정답은 아닌듯합니다. 
자바 api 중 package-private이 **잘 사용된** 예시를 알려주셨음 좋겠습니다!

제가 본 블로그도 공유합니다
[link](https://hyeon9mak.github.io/Java-dont-use-package-private/)
