### ISSUE TITLE
item15 : 자바 9 모듈시스템

### ISSUE THREAD

**Issue by ZhenxiKim** [WanOnPreStudy/EffectiveJavaStudy#29]
100 p : 자바 9에서는 모듈시스템이라는 개념이 도입되면서 두 가지 암묵적 접근 수준이 추가되었다.
처음 보는 내용이라 간략한 소개 부탁드립니다!
#24

**Comment by inhwanK** [comment]
관련해서 간략하게 정리된 글들을 공유합니다.  
- https://scshim.tistory.com/371
- https://iyoungman.github.io/java/Java9-Module/

대략 요약하자면,
- 이전 버전에서는 클래스, 패키지 수준에서만 코드 그룹화 및 가시성 제어를 제공한 반면, 패키지 간의 가시성 제어는 없었습니다.
- 클래스에서 private, public, protected 같은 접근 제어자를 통해 내부 멤버에 대한 접근을 제어를 하듯, 패키지(클래스의 멤버와 같은)를 모아놓은 모듈(클래스)이라는 것을 정의하고 이에 대한 접근 제어를 위한 시스템을 칭하는 것 같습니다.
- 이번 아이템에서 다룬 접근 제어자처럼 어떤 모듈에서 내부 패키지를 공개하려면 modul-info.java라는 파일에 'exports 패키지명'과 같은 구문으로 작성합니다.
- '두가지' 암묵적 접근 수준은
  1. 모듈의 패키지를 외부로 공개하지 않으면 public, protected로 공개된 클래스라도 외부 모듈에서는 접근할 수 없는 것
  2. 모듈의 jar 파일을 애플리케이션의 클래스패스에 두면 모듈 안의 패키지 공개여부와 상관 없이 public, protected 클래스에 모듈 밖에서 접근할 수 있게 되는 것

이 두가지를 말하는 것 같습니다. 책에는 말이 좀 어렵게 나와있는 것 같아요 ㅎ
결론은 자바9에서 패키지 단위의 새로운 접근 및 가시성 제어가 추가되었다. 라고 생각하면 될 것 같아요.
