### ISSUE TITLE
item15: 클래스 package-private이 잘 사용된 예시

### ISSUE THREAD

**Issue by gutenLEE** [WanOnPreStudy/EffectiveJavaStudy#30]
다른 블로그 글도 참고해보니 클래스 단위 접근제한을 무조건 package-private 으로 제한하는게 정답은 아닌듯합니다.
자바 api 중 package-private이 잘 사용된 예시를 알려주셨음 좋겠습니다!

제가 본 블로그도 공유합니다
[link](https://hyeon9mak.github.io/Java-dont-use-package-private/)

@inhwanK 
#24

**Comment by inhwanK** [comment]
죄송하지만 적절한 사례를 찾지는 못했습니다. 제가 모듈을 까봐도 잘 활용한 것인지 판단이 잘 안되네요 ㅠ
대신에 관련해서 괜찮은 글을 찾았습니다. 한번 읽어보시는 걸 추천드려용
- [7 Package-Private Best Practices](https://climbtheladder.com/7-package-private-best-practices)

요약
1. package-private 클래스는 다른 패키지에 표시되지 않으므로 자주 사용하면 안된다.
2. package-private 클래스를 사용하는 경우 패키지에서만 클래스에 액세스할 수 있는지 확인해라.
3. package-private 클래스에서 public 메소드를 만드는 것을 피하라.
4. package-private 클래스의 모든 데이터가 적절한 접근 제어자로 보호되는지 확인하라.
5. 가능한 한 package-private 클래스 대신 인터페이스를 사용하라.
6. 모든 package-private 클래스에 적절한 Javadoc 주석이 있는지 확인하라.
7. 보안을 위해 package-private 클래스에 의존하지 마라.

제 생각에는 package-private을 잘 사용하려면 패키지 구조나 다른 멤버들의 접근 제어 등이 적절하게 잘 되어있을 때, 그에 맞춰서 사용하는 것이 바람직한 것 같습니다.
공유해주신 글에서도 언급하듯이 실무에서는 package-private이 잘 활용될 수 있는 상황이 잘 오지 않는 것 같습니다.

**Comment by gutenLEE** [comment]
오 감사합니다!
