### ISSUE TITLE
item16: private 중첩 클래스 사용 예시

### ISSUE THREAD

**Issue by gutenLEE** [WanOnPreStudy/EffectiveJavaStudy#35]
중첩 클래스를 private으로 선언하면 중첩 클래스의 인스턴스 생성은 감싸는 클래스에서만 가능합니다. 
외부 클래스에서 중첩 클래스를 통해 가변 필드 접근을 어떻게 하는지 잘 모르겠습니다.

@ZhenxiKim

**Comment by ZhenxiKim** [comment]
```java
class OuterClass {
	String outerField = "Outer field";
	static String staticOuterField = "Static outer field";

	private class InnerClass {
		void accessMembers() {
			System.out.println(outerField);
			System.out.println(staticOuterField);
		}
	}

	public static void main(String[] args) {
		OuterClass outerObject = new OuterClass();
		OuterClass.InnerClass innerObject = outerObject.new InnerClass();
		innerObject.accessMembers();
	}
}
```
![Untitled](https://user-images.githubusercontent.com/45592236/210358542-827cc893-00d6-433c-a286-8b94e000d01b.png)

외부 클래스에서 중첩 클래스를 통해 가변 필드 접근이 불가한 이유는 내부 클래스의 경우 private으로 선언 하여 같은 클래스 내에서만 접근이 가능하므로 외부 클래스에서 중첩 클래스를 통해 접근이 되지 않는 것 같습니다.

---
추가 헷갈렸던 부분(p.103 두번째 단락)

> package-private클래스 혹은 private중첩 클래스라면 데이터 필드를 노출한다 해도 하등의 문제가 없다.
클래스 선언 면에서나 이를 사용하는 코드 면에서 접근자 방식보다 훨씬 깔끔하다.

→ public으로 선언된 클래스, 필드에 직접 접근하면 getter, setter메소드를 따로 선언하지 않기에 코드가 훨씬 깔끔하다라고 하는것 같습니다.

```java
class Product {
	public String productName;
	public int cost;
}
```

```java
class Order {
	private List<Product> productList;
	private int count;

	public Order(List<Product> productList, int count) {
		this.productList = productList;
		this.count = count;
	}

	public void calcProduct(Product product) {
		product.cost += 3000;
	}
}
```

> 클라이언트 코드가 클래스 내부 표현에 묶이기는 하나, 클라이언트도 어차피 이 클래스를 포함하는 패키지 안에서만 동작하는 코드이다.
> 

→ 위의 코드 예시에서 Product의 cost를 변경하고자 할 때 직접 가져다 쓰지만 내부표현으로 묶여 cost 필드가 변경되도 패키지 내부 클래스 들만 수정하면 된다는 의미?

> private 중첩 클래스의 경우라면 수정범위가 더 좁아져서 이 클래스를 포함하는 외부 클래스까지로 제한된다.
> 

→ private중첩 클래스의 경우 중첩클래스를 감싸는 외부 클래스에서만 접근이 가능하기에 수정 범위가 좁아진다는 뜻으로 이해했습니다.

**Comment by gutenLEE** [comment]
감사합니다!!! 이해했습니다!
