### ISSUE TITLE
아이템 20. 질문 - 믹스인

### ISSUE THREAD

**Issue by inhwanK** [WanOnPreStudy/EffectiveJavaStudy#57]
'오브젝트' 책에서도 읽었던 내용이긴 한데, 믹스인이라는 개념이 추상적으로만 들려서요.
믹스인을 구현한? 사용한? 구체적인 예시나 코드가 있을까요?

**Comment by jueun275** [comment]
</br>

## 오브젝트에서의 믹스인
먼저 제가 오브젝트의 믹스인 부분을 확인해 봤는데 오브젝트의 코드는 스칼라의 `trait`을  사용하여 구현 하더라구요 .
**`trait`과 `interface`는 문법의 차이가** 존재하기 때문에 이펙티브 자바에서 나오는 믹스인 인터페이스를 오프젝트에 나오는 믹스인 기법으로 이해하려고 하면 어려울거 같습니다.


### trait     
 https://hamait.tistory.com/602
*  Scala 는 interface 가 없으며 대신  trait 을 사용한다. 

*  Scala 의 trait 는 자바의 interface 와 달리 구현 가능하다. (자바8 부터는 자바인터페이스도 디폴트메소드등 구현)

*  하나의 부모클래스를 갖는 클래스의 상속과 달리 트레이트는 몇개라도 조합해 사용 가능하다.

 * Scala 의 trait 는 자바의  인터페이스와 추상클래스의 장점을 섞었다. 

 * 트레이트를 믹스인 할때는 extends 키워드를 이용한다. 

 * extends 를 사용하면 trait 의 슈퍼클래스를 암시적으로 상속하고 , 본래 trait 를 믹스인한다. 

*  trait 는 어떤 슈퍼클래스를 명시적으로 상속한 클래스에 혼합할 수 있다. 

   그때 슈퍼클래스는 extends 를 사용하고, trait 는 with 로 믹스인 한다

</br>


## 이펙티브 자바에서 믹스인
>예컨데 Comparable은 자신을 구현한 클래스의 인스턴스들끼리는 순서를 정할 수 있다고 선언하는 믹스인 인터페이스다.
> 이처럼  대상 타입의 주된  기능에 선택적 기능을 혼합(mixed-in)하는 것이다. 


즉 어떤 주기능 A를 제공하는데 선택 기능 B를 제공하여 기능을 혼합할 수 있다는 것을 의미

#### **오브젝트에서의 믹스인 예제(p381)도 기본 정책이라는 주 기능이 있고 부가 정책이라는 선택적 기능을  혼합한다 의  개념 정도로만 이해하는게 좋을것 같습니다!** 

</br>

### 예제코드
예로는 책에서 나온 Comparable 인터페이스를 보겠습니다.
Comparable 인터페이스는 객체를 정렬하는 데 사용되는 메서드인 ```compareTo()``` 메서드를 정의하고 있습니다.
자바에서 같은 타입의 인스턴스를 서로 비교해야만 하는 클래스들은 모두 Comparable 인터페이스를 구현하고 있습니다.
따라서 Boolean을 제외한 래퍼 클래스나 String, Time, Date와 같은 클래스의 인스턴스는 모두 정렬 가능합니다

</br>

- **java.lang.Comparable  인터페이스**

```java
public interface Comparable<T> {
    public int compareTo(T o);
}
```

</br>

- **java.lang.Integer 클래스**
```java

public final class Integer extends Number implements Comparable<Integer> {

    public int compareTo(Integer anotherInteger) {
        return compare(this.value, anotherInteger.value);
    }
}
```
</br>

위 예를 보면 Integer 클래스는 Number이라는 추상 클래스를 상속하면서 Comparable 인터페이스를 구현하고 있습니다.

만약 Comparable이 추상 메서드 였다면..?

```java
abstract class comparable {
    abstract int compareTo(Object o);
}
```

단일 상속이 원칙인 자바에서는 comparable 클래스를 상속할 수 없을 것 입니다.

또 다른 믹스인 인터페이스
- 복제해도 되는 클래스임을 명시하는 용도의 Cloneable
- 직렬화 할 수 있는 클래스임을 명시하는 Serializable 
- Iterable , AutoCloseable  등등
</br>

**java.util.Date 클래스**

```java
public class Date
    implements java.io.Serializable, Cloneable, Comparable<Date>
```

Date 클래스의 경우로 여러 믹스인 인터페이스 들을 구현하고 있는데 이들이 추상메서드 였다면 이 역시 불가능 할 것입니다.

</br>

**Comment by inhwanK** [comment]
감사합니당
